export const difficultyOptions = ['All', 'Easy', 'Medium', 'Hard']

export const languageOptions = ['All', 'JavaScript', 'TypeScript', 'Python', 'SQL']

export const challengeItems = [
  {
    id: 'two-sum-stream',
    title: 'Two Sum in Data Stream',
    description: 'Detect whether any pair in a stream adds up to a target value in near-constant time.',
    difficulty: 'Easy',
    language: 'JavaScript',
    estimatedTime: '20 min',
  },
  {
    id: 'retry-backoff',
    title: 'Retry with Exponential Backoff',
    description: 'Build a resilient async retry helper with jitter and max-attempt controls.',
    difficulty: 'Medium',
    language: 'TypeScript',
    estimatedTime: '30 min',
  },
  {
    id: 'sql-report',
    title: 'Users and Orders SQL Report',
    description: 'Create a performant query for top-spending users with clean grouping and sorting.',
    difficulty: 'Hard',
    language: 'SQL',
    estimatedTime: '45 min',
  },
  {
    id: 'grid-islands',
    title: 'Count Islands in Grid',
    description: 'Traverse a matrix and count connected components using DFS or BFS.',
    difficulty: 'Easy',
    language: 'Python',
    estimatedTime: '25 min',
  },
  {
    id: 'string-normalizer',
    title: 'Normalize User Handles',
    description: 'Sanitize and normalize usernames while preserving expected symbols and constraints.',
    difficulty: 'Easy',
    language: 'JavaScript',
    estimatedTime: '18 min',
  },
  {
    id: 'event-bus',
    title: 'Typed Event Bus',
    description: 'Implement a pub/sub event bus with strict TypeScript payload typing and unsubscribe support.',
    difficulty: 'Medium',
    language: 'TypeScript',
    estimatedTime: '35 min',
  },
  {
    id: 'debounced-search',
    title: 'Debounced Search Endpoint',
    description: 'Build client and API coordination for debounced search with cancelation and stale response guards.',
    difficulty: 'Medium',
    language: 'TypeScript',
    estimatedTime: '28 min',
  },
  {
    id: 'pagination-window',
    title: 'Sliding Pagination Window',
    description: 'Generate stable pagination ranges for large datasets while handling first and last pages.',
    difficulty: 'Easy',
    language: 'JavaScript',
    estimatedTime: '22 min',
  },
  {
    id: 'orm-bulk-update',
    title: 'Safe Bulk Update Script',
    description: 'Write a transactional migration script that updates large records in batches without lock issues.',
    difficulty: 'Hard',
    language: 'SQL',
    estimatedTime: '50 min',
  },
  {
    id: 'ranking-query',
    title: 'Leaderboard Ranking Query',
    description: 'Use window functions to compute rank positions with tie handling and pagination.',
    difficulty: 'Medium',
    language: 'SQL',
    estimatedTime: '32 min',
  },
  {
    id: 'log-parser',
    title: 'Streaming Log Parser',
    description: 'Parse large log files line by line and emit grouped error summaries by service.',
    difficulty: 'Medium',
    language: 'Python',
    estimatedTime: '34 min',
  },
  {
    id: 'top-k-frequent',
    title: 'Top K Frequent Elements',
    description: 'Return the K most frequent values using a heap-based approach with strong complexity guarantees.',
    difficulty: 'Medium',
    language: 'Python',
    estimatedTime: '27 min',
  },
  {
    id: 'cache-invalidation',
    title: 'Cache Invalidation Strategy',
    description: 'Design a cache key strategy with selective invalidation when related resources are updated.',
    difficulty: 'Hard',
    language: 'TypeScript',
    estimatedTime: '48 min',
  },
  {
    id: 'jwt-refresh-flow',
    title: 'JWT Refresh Session Flow',
    description: 'Implement secure refresh token rotation with replay protection and session revocation.',
    difficulty: 'Hard',
    language: 'JavaScript',
    estimatedTime: '55 min',
  },
  {
    id: 'binary-search-answer',
    title: 'Binary Search on Answer',
    description: 'Solve optimization constraints by applying binary search to an implicit answer space.',
    difficulty: 'Medium',
    language: 'Python',
    estimatedTime: '29 min',
  },
  {
    id: 'schema-evolution',
    title: 'Schema Evolution Plan',
    description: 'Plan backward-compatible database schema changes across rolling deployments.',
    difficulty: 'Hard',
    language: 'SQL',
    estimatedTime: '42 min',
  },
]
