"""add_missing_file_columns

Revision ID: 3657143b9ea9
Revises: zenith_002
Create Date: 2026-02-28 02:00:00.904519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3657143b9ea9'
down_revision: Union[str, None] = 'zenith_002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('url', sa.String(length=500), nullable=True))
    op.add_column('files', sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True))
    op.add_column('files', sa.Column('file_type', sa.String(length=50), nullable=False))
    op.add_column('files', sa.Column('format', sa.String(length=50), nullable=True))
    op.alter_column('files', 'description',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('files', 'mime_type',
               existing_type=sa.VARCHAR(length=127),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('files', 'path',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('files', 'size',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.drop_index('ix_files_user_id', table_name='files')
    op.create_index(op.f('ix_files_cloudinary_public_id'), 'files', ['cloudinary_public_id'], unique=True)
    op.create_index(op.f('ix_files_path'), 'files', ['path'], unique=False)
    op.drop_column('files', 'uploaded_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_files_path'), table_name='files')
    op.drop_index(op.f('ix_files_cloudinary_public_id'), table_name='files')
    op.create_index('ix_files_user_id', 'files', ['user_id'], unique=False)
    op.alter_column('files', 'size',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('files', 'path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('files', 'mime_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=127),
               existing_nullable=True)
    op.alter_column('files', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.drop_column('files', 'format')
    op.drop_column('files', 'file_type')
    op.drop_column('files', 'cloudinary_public_id')
    op.drop_column('files', 'url')
    # ### end Alembic commands ###
