"""add summary column to files

Revision ID: 5cb1ed639e6f
Revises: f30b257f2163
Create Date: 2026-02-28 11:23:36.369465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb1ed639e6f'
down_revision: Union[str, None] = 'f30b257f2163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'summary')
    # ### end Alembic commands ###
