"""Add challenge messages and creator

Revision ID: eb354e2512a8
Revises: 372bee75c6e8
Create Date: 2026-02-23 21:29:00.021090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb354e2512a8'
down_revision: Union[str, None] = '372bee75c6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_messages_challenge_id'), 'challenge_messages', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_messages_id'), 'challenge_messages', ['id'], unique=False)
    op.create_index(op.f('ix_challenge_messages_user_id'), 'challenge_messages', ['user_id'], unique=False)
    op.add_column('challenges', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_challenges_creator_id'), 'challenges', ['creator_id'], unique=False)
    op.create_foreign_key(None, 'challenges', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challenges', type_='foreignkey')
    op.drop_index(op.f('ix_challenges_creator_id'), table_name='challenges')
    op.drop_column('challenges', 'creator_id')
    op.drop_index(op.f('ix_challenge_messages_user_id'), table_name='challenge_messages')
    op.drop_index(op.f('ix_challenge_messages_id'), table_name='challenge_messages')
    op.drop_index(op.f('ix_challenge_messages_challenge_id'), table_name='challenge_messages')
    op.drop_table('challenge_messages')
    # ### end Alembic commands ###
