"""add snippet to files

Revision ID: ee05bc1be143
Revises: 5cb1ed639e6f
Create Date: 2026-02-28 23:35:27.058395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee05bc1be143'
down_revision: Union[str, None] = '5cb1ed639e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('snippet', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'snippet')
    # ### end Alembic commands ###
